
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 24 2024 13:39:07 IST (Jun 24 2024 08:09:07 UTC)

// Verification Directory fv/dadda 

module hag(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0;
  INVX2 g26(.A (n_0), .Y (c));
  AOI2BB1XL g27__2398(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  NAND2X2 g29__5107(.A (b), .B (a), .Y (n_0));
endmodule

module hag_105(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  CMPR22X1 g28__6260(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g258__4319(.A0N (b), .A1N (cin), .B0 (n_1), .Y (c));
  XOR2X1 g259__8428(.A (n_0), .B (a), .Y (s));
  OAI21XL g260__5526(.A0 (cin), .A1 (b), .B0 (a), .Y (n_1));
  XOR2X1 g261__6783(.A (cin), .B (b), .Y (n_0));
endmodule

module hag_104(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  XOR2X2 g2__1617(.A (b), .B (a), .Y (s));
  AND2X2 g2(.A (b), .B (a), .Y (c));
endmodule

module fag_92(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X2 g90__2802(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X1 g91__1705(.S0 (cin), .B (n_1), .A (n_2), .Y (s));
  OAI21XL g92__5122(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  INVX1 g93(.A (n_1), .Y (n_2));
  MXI2X1 g94__8246(.S0 (a), .B (b), .A (n_0), .Y (n_1));
  INVX1 g95(.A (b), .Y (n_0));
endmodule

module fag_91(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire UNCONNECTED, n_0, n_1;
  OAI2BB1X2 g256__7098(.A0N (b), .A1N (cin), .B0 (n_1), .Y (c));
  OAI21XL g258__1881(.A0 (cin), .A1 (b), .B0 (a), .Y (n_1));
  XOR2X1 g259__5115(.A (cin), .B (b), .Y (n_0));
  ADDHX1 g257__261(.A (n_0), .B (a), .S (s), .CO (UNCONNECTED));
endmodule

module hag_103(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0, n_1;
  CLKINVX3 g28(.A (n_1), .Y (c));
  MXI2X2 g29__7482(.S0 (b), .B (a), .A (n_0), .Y (s));
  NAND2X2 g30__4733(.A (b), .B (a), .Y (n_1));
  CLKINVX3 g31(.A (a), .Y (n_0));
endmodule

module fag_90(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X2 g129__6161(.A0N (n_0), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X2 g130__9315(.S0 (n_4), .B (a), .A (n_2), .Y (s));
  MXI2X1 g131__9945(.S0 (b), .B (cin), .A (n_1), .Y (n_4));
  NAND2X1 g133__2883(.A (cin), .B (b), .Y (n_3));
  INVX1 g134(.A (a), .Y (n_2));
  CLKINVX3 g136(.A (cin), .Y (n_1));
  NAND2BX1 g2__2346(.AN (b), .B (n_1), .Y (n_0));
endmodule

module fag_89(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire UNCONNECTED0, n_0, n_2, n_3;
  MXI2X2 g94__1666(.S0 (a), .B (n_2), .A (n_0), .Y (s));
  OAI2BB1X2 g95__7410(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  OAI21XL g96__6417(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  INVX1 g97(.A (n_0), .Y (n_2));
  AHHCINX2 g102__5477(.A (cin), .CIN (b), .S (n_0), .CO (UNCONNECTED0));
endmodule

module fag_88(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_2;
  OAI2BB1X1 g167__2398(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  OAI21X1 g169__5107(.A0 (a), .A1 (b), .B0 (cin), .Y (n_2));
  XNOR2X1 g2__6260(.A (n_0), .B (cin), .Y (s));
  XNOR2X1 g174__4319(.A (a), .B (b), .Y (n_0));
endmodule

module fag_87(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI21X2 g133__8428(.A0 (n_3), .A1 (n_1), .B0 (n_2), .Y (c));
  MXI2X2 g134__5526(.S0 (n_4), .B (cin), .A (n_1), .Y (s));
  MXI2X2 g135__6783(.S0 (a), .B (b), .A (n_0), .Y (n_4));
  NOR2X1 g136__3680(.A (a), .B (b), .Y (n_3));
  NAND2X1 g137__1617(.A (b), .B (a), .Y (n_2));
  CLKINVX3 g138(.A (cin), .Y (n_1));
  CLKINVX3 g139(.A (b), .Y (n_0));
endmodule

module fag_86(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X2 g160__2802(.A0N (b), .A1N (cin), .B0 (n_2), .Y (c));
  MXI2X2 g161__1705(.S0 (n_0), .B (a), .A (n_1), .Y (s));
  OAI21XL g162__5122(.A0 (b), .A1 (cin), .B0 (a), .Y (n_2));
  CLKINVX3 g164(.A (a), .Y (n_1));
  XOR2X2 g2__8246(.A (cin), .B (b), .Y (n_0));
endmodule

module hag_102(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g28__7098(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_85(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  MXI2X2 g109__6131(.S0 (n_0), .B (n_3), .A (a), .Y (s));
  OAI22X1 g110__1881(.A0 (n_5), .A1 (n_2), .B0 (n_4), .B1 (n_1), .Y
       (c));
  NOR2X1 g112__5115(.A (a), .B (b), .Y (n_5));
  INVX1 g113(.A (a), .Y (n_4));
  INVX1 g114(.A (a), .Y (n_3));
  INVX1 g115(.A (cin), .Y (n_2));
  INVX1 g117(.A (b), .Y (n_1));
  XNOR2X2 g2__7482(.A (cin), .B (b), .Y (n_0));
endmodule

module fag_84(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_2, n_3, n_4;
  OAI21X2 g170__4733(.A0 (n_4), .A1 (n_2), .B0 (n_3), .Y (c));
  NOR2X2 g174__6161(.A (a), .B (b), .Y (n_4));
  NAND2X1 g175__9315(.A (a), .B (b), .Y (n_3));
  INVX1 g176(.A (cin), .Y (n_2));
  MXI2XL g2__9945(.S0 (n_0), .B (n_2), .A (cin), .Y (s));
  XNOR2X1 g178__2883(.A (a), .B (b), .Y (n_0));
endmodule

module hag_101(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire UNCONNECTED1;
  ADDHX1 g33__1666(.A (a), .B (b), .S (s), .CO (UNCONNECTED1));
  AND2X2 g2(.A (b), .B (a), .Y (c));
endmodule

module fag_83(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_4, n_14;
  OAI2BB1X2 g92__7410(.A0N (n_4), .A1N (cin), .B0 (n_0), .Y (c));
  OAI2BB2X2 g93__6417(.A0N (n_14), .A1N (cin), .B0 (cin), .B1 (n_14),
       .Y (s));
  NAND2X1 g95__2398(.A (n_2), .B (n_1), .Y (n_4));
  INVX1 g99(.A (a), .Y (n_2));
  CLKINVX3 g100(.A (b), .Y (n_1));
  NAND2BX1 g2__5107(.AN (n_2), .B (b), .Y (n_0));
  MXI2X1 g2(.S0 (a), .B (n_1), .A (b), .Y (n_14));
endmodule

module fag_82(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFHX4 g2(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_81(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g138__3680(.A0N (n_0), .A1N (a), .B0 (n_1), .Y (c));
  XOR3X2 g139__1617(.A (cin), .B (a), .C (b), .Y (s));
  OAI21X1 g140__2802(.A0 (a), .A1 (n_0), .B0 (b), .Y (n_1));
  BUFX3 g141(.A (cin), .Y (n_0));
endmodule

module fag_80(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_2;
  XOR3X2 g109__1705(.A (cin), .B (b), .C (a), .Y (s));
  OAI2BB1X2 g110__5122(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  OAI21XL g111__8246(.A0 (b), .A1 (a), .B0 (cin), .Y (n_2));
endmodule

module fag_79(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_3, n_4, n_5;
  OAI2BB1X2 g110__7098(.A0N (b), .A1N (a), .B0 (n_5), .Y (c));
  OAI21X1 g112__6131(.A0 (a), .A1 (b), .B0 (cin), .Y (n_5));
  MXI2X1 g114__1881(.S0 (b), .B (n_1), .A (a), .Y (n_4));
  INVX1 g116(.A (cin), .Y (n_3));
  INVX1 g118(.A (a), .Y (n_1));
  XOR2X1 g2__5115(.A (n_4), .B (n_3), .Y (s));
endmodule

module fag_78(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X1 g115__7482(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X2 g116__4733(.S0 (n_2), .B (cin), .A (n_1), .Y (s));
  OAI21XL g117__6161(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  MXI2X2 g118__9315(.S0 (a), .B (b), .A (n_0), .Y (n_2));
  INVX1 g119(.A (cin), .Y (n_1));
  CLKINVX3 g120(.A (b), .Y (n_0));
endmodule

module hag_100(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g28__9945(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_77(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X1 g115__2883(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X1 g116__2346(.S0 (n_2), .B (cin), .A (n_1), .Y (s));
  OAI21XL g117__1666(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  MXI2X1 g118__7410(.S0 (a), .B (b), .A (n_0), .Y (n_2));
  INVX1 g119(.A (cin), .Y (n_1));
  CLKINVX3 g120(.A (b), .Y (n_0));
endmodule

module fag_76(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire UNCONNECTED2, n_0, n_1, n_2;
  OAI2BB1X2 g138__6417(.A0N (cin), .A1N (b), .B0 (n_2), .Y (c));
  MXI2X2 g139__5477(.S0 (n_0), .B (a), .A (n_1), .Y (s));
  OAI21XL g140__2398(.A0 (b), .A1 (cin), .B0 (a), .Y (n_2));
  CLKINVX3 g142(.A (a), .Y (n_1));
  CMPR22X1 g145__5107(.A (cin), .B (b), .S (n_0), .CO (UNCONNECTED2));
endmodule

module fag_75(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X1 g63__6260(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  MXI2X2 g64__4319(.S0 (n_0), .B (cin), .A (n_1), .Y (s));
  OAI21XL g65__8428(.A0 (a), .A1 (b), .B0 (cin), .Y (n_2));
  INVX1 g67(.A (cin), .Y (n_1));
  XOR2X1 g2__5526(.A (b), .B (a), .Y (n_0));
endmodule

module fag_74(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  MXI2X2 g73__6783(.S0 (n_2), .B (a), .A (n_1), .Y (s));
  OAI2BB1X1 g74__3680(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  OAI21XL g75__1617(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  MXI2X1 g76__2802(.S0 (b), .B (cin), .A (n_0), .Y (n_2));
  INVX1 g77(.A (a), .Y (n_1));
  INVX1 g78(.A (cin), .Y (n_0));
endmodule

module fag_73(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  MXI2X2 g109__1705(.S0 (n_3), .B (n_2), .A (a), .Y (s));
  OAI2BB1X2 g110__5122(.A0N (b), .A1N (a), .B0 (n_4), .Y (c));
  OAI21XL g111__8246(.A0 (a), .A1 (b), .B0 (cin), .Y (n_4));
  AOI22X2 g112__7098(.A0 (b), .A1 (n_1), .B0 (n_0), .B1 (cin), .Y
       (n_3));
  INVX1 g113(.A (a), .Y (n_2));
  INVX1 g114(.A (cin), .Y (n_1));
  CLKINVX3 g115(.A (b), .Y (n_0));
endmodule

module fag_72(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_2, n_3, n_4, n_5;
  OAI2BB1X4 g110__6131(.A0N (n_0), .A1N (cin), .B0 (n_4), .Y (c));
  MXI2X1 g113__1881(.S0 (b), .B (a), .A (n_2), .Y (n_5));
  NAND2X1 g115__5115(.A (a), .B (b), .Y (n_4));
  INVX1 g117(.A (cin), .Y (n_3));
  CLKINVX3 g118(.A (a), .Y (n_2));
  XNOR2X1 g2__7482(.A (n_3), .B (n_5), .Y (s));
  NAND2BX1 g120__4733(.AN (b), .B (n_2), .Y (n_0));
endmodule

module fag_71(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  XOR3X2 g109__6161(.A (cin), .B (a), .C (b), .Y (s));
  OAI2BB1X1 g110__9315(.A0N (a), .A1N (b), .B0 (n_0), .Y (c));
  OAI21XL g111__9945(.A0 (b), .A1 (a), .B0 (cin), .Y (n_0));
endmodule

module fag_70(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_2, n_4, n_5, n_11;
  OAI2BB1X2 g107__2883(.A0N (n_11), .A1N (cin), .B0 (n_2), .Y (c));
  MXI2X1 g108__2346(.S0 (cin), .B (n_5), .A (n_4), .Y (s));
  INVX2 g109(.A (n_4), .Y (n_5));
  MXI2X2 g110__1666(.S0 (a), .B (n_0), .A (b), .Y (n_4));
  NAND2XL g112__6417(.A (a), .B (b), .Y (n_2));
  CLKINVX3 g114(.A (b), .Y (n_0));
  NAND2BX1 g2(.AN (a), .B (n_0), .Y (n_11));
endmodule

module fag_69(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X2 g63__5477(.A0N (n_3), .A1N (cin), .B0 (n_2), .Y (c));
  OAI2BB2X2 g64__2398(.A0N (n_4), .A1N (cin), .B0 (cin), .B1 (n_4), .Y
       (s));
  AOI22X1 g65__5107(.A0 (n_0), .A1 (a), .B0 (b), .B1 (n_1), .Y (n_4));
  NAND2X1 g66__6260(.A (n_0), .B (n_1), .Y (n_3));
  NAND2X1 g67__4319(.A (b), .B (a), .Y (n_2));
  INVX1 g68(.A (a), .Y (n_1));
  INVX1 g69(.A (b), .Y (n_0));
endmodule

module right_da(p, a, b);
  input [7:0] a, b;
  output [10:0] p;
  wire [7:0] a, b;
  wire [10:0] p;
  wire [56:1] d;
  wire [7:0] l;
  wire [22:0] s;
  wire [22:0] c;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_63, n_72;
  hag r1(p[1], l[0], d[1], d[8]);
  hag_105 r2(s[16], c[16], d[2], d[9]);
  fag r3(p[2], l[1], s[16], d[16], l[0]);
  hag_104 r4(s[10], c[10], d[3], d[10]);
  fag_92 r5(s[17], c[17], d[17], d[24], s[10]);
  fag_91 r6(p[3], l[2], s[17], c[16], l[1]);
  hag_103 r7(s[3], c[3], d[4], d[11]);
  fag_90 r8(s[11], c[11], s[3], d[18], d[25]);
  fag_89 r9(s[18], c[18], s[11], d[32], c[10]);
  fag_88 r10(p[4], l[3], s[18], c[17], l[2]);
  fag_87 r11(s[4], c[4], d[5], d[12], d[19]);
  fag_86 r12(s[12], c[12], s[4], c[3], s[7]);
  hag_102 r13(s[7], c[7], d[26], d[33]);
  fag_85 r14(s[19], c[19], s[12], c[11], d[40]);
  fag_84 r15(p[5], l[4], s[19], c[18], l[3]);
  hag_101 r16(s[0], c[0], d[6], d[13]);
  fag_83 r17(s[5], c[5], n_63, d[27], s[0]);
  fag_82 r18(s[8], c[8], d[34], n_72, d[48]);
  fag_81 r19(s[13], c[13], s[8], s[5], c[4]);
  fag_80 r20(s[20], c[20], s[13], c[12], c[7]);
  fag_79 r21(p[6], l[5], s[20], c[19], l[4]);
  fag_78 r22(s[1], c[1], d[7], d[14], d[21]);
  hag_100 r23(s[2], c[2], d[28], d[35]);
  fag_77 r24(s[9], c[9], d[42], d[49], d[56]);
  fag_76 r25(s[6], c[6], s[1], s[2], c[0]);
  fag_75 r26(s[15], c[15], c[1], c[2], c[6]);
  fag_74 r27(s[14], c[14], s[6], c[5], s[9]);
  fag_73 r28(s[21], c[21], s[14], c[13], c[8]);
  fag_72 r29(p[7], l[6], s[21], c[20], l[5]);
  fag_71 r30(s[22], c[22], s[15], c[14], c[9]);
  fag_70 r31(p[8], l[7], s[22], c[21], l[6]);
  fag_69 r32(p[9], p[10], c[15], c[22], l[7]);
  INVX2 g364(.A (n_15), .Y (d[1]));
  INVX4 g365(.A (n_14), .Y (d[6]));
  INVX4 g368(.A (n_13), .Y (d[33]));
  INVX4 g371(.A (n_12), .Y (d[12]));
  INVX4 g372(.A (n_11), .Y (d[5]));
  INVX4 g375(.A (n_10), .Y (d[14]));
  NAND2X4 g380__8428(.A (a[1]), .B (b[0]), .Y (n_15));
  NAND2X2 g381__5526(.A (a[6]), .B (b[0]), .Y (n_14));
  AND2X2 g383__6783(.A (a[0]), .B (b[5]), .Y (d[40]));
  NAND2X2 g385__3680(.A (a[1]), .B (b[4]), .Y (n_13));
  AND2X2 g386__1617(.A (a[0]), .B (b[0]), .Y (p[0]));
  NAND2X4 g389__2802(.A (a[4]), .B (b[1]), .Y (n_12));
  NAND2X2 g390__1705(.A (a[5]), .B (b[0]), .Y (n_11));
  NAND2X2 g393__5122(.A (a[6]), .B (b[1]), .Y (n_10));
  INVX4 g396(.A (n_8), .Y (d[4]));
  INVX4 g398(.A (n_7), .Y (d[10]));
  INVX4 g399(.A (n_6), .Y (d[3]));
  CLKINVX3 g400(.A (n_5), .Y (d[13]));
  INVX2 g404(.A (n_4), .Y (d[11]));
  INVX2 g406(.A (n_3), .Y (d[7]));
  INVX2 g408(.A (n_2), .Y (d[8]));
  INVX2 g411(.A (n_1), .Y (d[34]));
  NAND2X4 g414__7098(.A (a[4]), .B (b[0]), .Y (n_8));
  NAND2X2 g416__6131(.A (a[2]), .B (b[1]), .Y (n_7));
  NAND2X2 g417__1881(.A (a[3]), .B (b[0]), .Y (n_6));
  NAND2X2 g418__5115(.A (a[5]), .B (b[1]), .Y (n_5));
  NAND2X2 g422__7482(.A (a[3]), .B (b[1]), .Y (n_4));
  NAND2X2 g424__4733(.A (a[7]), .B (b[0]), .Y (n_3));
  NAND2X2 g426__6161(.A (a[0]), .B (b[1]), .Y (n_2));
  NAND2X4 g429__9315(.A (a[2]), .B (b[4]), .Y (n_1));
  AND2X4 g2__2883(.A (a[3]), .B (b[2]), .Y (d[19]));
  AND2X2 g431__2346(.A (a[0]), .B (b[7]), .Y (d[56]));
  AND2X2 g432__1666(.A (a[2]), .B (b[5]), .Y (d[42]));
  AND2X2 g433__7410(.A (a[2]), .B (b[0]), .Y (d[2]));
  AND2X2 g434__6417(.A (a[0]), .B (b[2]), .Y (d[16]));
  AND2X2 g435__5477(.A (a[5]), .B (b[2]), .Y (d[21]));
  AND2X4 g436__2398(.A (a[0]), .B (b[3]), .Y (d[24]));
  AND2X4 g437__5107(.A (a[0]), .B (b[4]), .Y (d[32]));
  AND2X4 g438__6260(.A (a[1]), .B (b[3]), .Y (d[25]));
  AND2X4 g439__4319(.A (a[2]), .B (b[2]), .Y (d[18]));
  AND2X2 g440__8428(.A (a[1]), .B (b[2]), .Y (d[17]));
  AND2X4 g441__5526(.A (a[1]), .B (b[6]), .Y (d[49]));
  AND2X4 g442__6783(.A (a[3]), .B (b[3]), .Y (d[27]));
  AND2X4 g443__3680(.A (a[3]), .B (b[4]), .Y (d[35]));
  AND2X2 g444__1617(.A (a[2]), .B (b[3]), .Y (d[26]));
  AND2X4 g445__2802(.A (a[1]), .B (b[1]), .Y (d[9]));
  AND2X2 g446__1705(.A (a[0]), .B (b[6]), .Y (d[48]));
  AND2X2 g447__5122(.A (a[4]), .B (b[3]), .Y (d[28]));
  AND2X2 g2(.A (a[4]), .B (b[2]), .Y (n_63));
  AND2X2 g456(.A (a[1]), .B (b[5]), .Y (n_72));
endmodule

module hag_99(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_1;
  MXI2X4 g29__8246(.S0 (b), .B (a), .A (n_1), .Y (s));
  CLKINVX3 g31(.A (a), .Y (n_1));
  AND2X4 g2__7098(.A (a), .B (b), .Y (c));
endmodule

module fag_68(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X4 g173__6131(.A0N (cin), .A1N (b), .B0 (n_4), .Y (c));
  MXI2X4 g174__1881(.S0 (n_3), .B (a), .A (n_2), .Y (s));
  OAI21X2 g175__5115(.A0 (b), .A1 (cin), .B0 (a), .Y (n_4));
  OAI2BB1X2 g176__7482(.A0N (b), .A1N (n_1), .B0 (n_0), .Y (n_3));
  CLKINVX3 g178(.A (a), .Y (n_2));
  INVX1 g180(.A (cin), .Y (n_1));
  NAND2BX2 g2__4733(.AN (b), .B (cin), .Y (n_0));
endmodule

module hag_98(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0, n_1, n_2;
  INVX4 g28(.A (n_2), .Y (c));
  AOI22X2 g29__6161(.A0 (n_0), .A1 (n_1), .B0 (a), .B1 (b), .Y (s));
  NAND2X4 g30__9315(.A (a), .B (b), .Y (n_2));
  INVX1 g31(.A (b), .Y (n_1));
  INVX2 g32(.A (a), .Y (n_0));
endmodule

module hag_97(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g28__9945(.A (b), .B (a), .S (s), .CO (c));
endmodule

module hag_96(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0, n_1;
  AOI2BB1X1 g26__2883(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  NOR2X2 g27__2346(.A (n_0), .B (n_1), .Y (c));
  INVX1 g28(.A (b), .Y (n_1));
  INVX2 g29(.A (a), .Y (n_0));
endmodule

module hag_95(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_14;
  INVX4 g28(.A (n_14), .Y (c));
  AHHCONX2 g37(.A (b), .CI (a), .S (s), .CON (n_14));
endmodule

module fag_67(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_3, n_8;
  NAND2X1 g111__2398(.A (a), .B (b), .Y (n_3));
  XOR3X4 g2__6260(.A (cin), .B (b), .C (a), .Y (s));
  NAND2X1 g2(.A (n_8), .B (n_3), .Y (c));
  OAI21X1 g3(.A0 (a), .A1 (b), .B0 (cin), .Y (n_8));
endmodule

module hag_94(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  CMPR22X1 g28__4319(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_66(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  OAI2BB1X2 g148__8428(.A0N (n_4), .A1N (b), .B0 (n_0), .Y (c));
  MXI2X4 g149__5526(.S0 (n_5), .B (b), .A (n_3), .Y (s));
  MXI2X4 g150__6783(.S0 (a), .B (cin), .A (n_1), .Y (n_5));
  NAND2X1 g151__3680(.A (n_1), .B (n_2), .Y (n_4));
  INVX2 g153(.A (b), .Y (n_3));
  INVX1 g155(.A (a), .Y (n_2));
  INVX4 g156(.A (cin), .Y (n_1));
  NAND2BX1 g2__1617(.AN (n_2), .B (cin), .Y (n_0));
endmodule

module fag_65(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  MXI2X1 g109__2802(.S0 (n_5), .B (n_2), .A (a), .Y (s));
  OAI21X1 g110__1705(.A0 (n_3), .A1 (n_1), .B0 (n_4), .Y (c));
  MXI2X2 g111__5122(.S0 (cin), .B (n_0), .A (b), .Y (n_5));
  NAND2X1 g112__8246(.A (a), .B (b), .Y (n_4));
  NOR2X1 g113__7098(.A (a), .B (b), .Y (n_3));
  INVX2 g114(.A (a), .Y (n_2));
  INVX1 g115(.A (cin), .Y (n_1));
  INVX1 g116(.A (b), .Y (n_0));
endmodule

module fag_64(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X2 g256__6131(.A0N (b), .A1N (cin), .B0 (n_2), .Y (c));
  OAI2BB2X1 g257__1881(.A0N (a), .A1N (n_0), .B0 (n_0), .B1 (a), .Y
       (s));
  OAI21X1 g258__5115(.A0 (cin), .A1 (b), .B0 (a), .Y (n_2));
  BUFX2 g263(.A (cin), .Y (n_1));
  XNOR2X1 g2__7482(.A (n_1), .B (b), .Y (n_0));
endmodule

module fag_63(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_2, n_3;
  OAI2BB1X2 g102__4733(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  OAI21XL g104__6161(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  MXI2X2 g105__9315(.S0 (a), .B (b), .A (n_1), .Y (n_2));
  CLKINVX3 g107(.A (b), .Y (n_1));
  XOR2X2 g2__9945(.A (n_2), .B (cin), .Y (s));
endmodule

module fag_62(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X1 g115__2883(.A0N (a), .A1N (b), .B0 (n_4), .Y (c));
  MXI2X4 g116__2346(.S0 (n_3), .B (cin), .A (n_2), .Y (s));
  OAI21XL g117__1666(.A0 (a), .A1 (b), .B0 (cin), .Y (n_4));
  OAI2BB1X4 g118__7410(.A0N (a), .A1N (n_1), .B0 (n_0), .Y (n_3));
  INVX1 g120(.A (cin), .Y (n_2));
  INVX1 g122(.A (b), .Y (n_1));
  NAND2BX2 g2__6417(.AN (a), .B (b), .Y (n_0));
endmodule

module fag_61(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X1 g102__5477(.A0N (a), .A1N (b), .B0 (n_4), .Y (c));
  MXI2X1 g103__2398(.S0 (n_3), .B (n_2), .A (cin), .Y (s));
  OAI21XL g104__5107(.A0 (b), .A1 (a), .B0 (cin), .Y (n_4));
  AOI22X1 g105__6260(.A0 (n_0), .A1 (a), .B0 (n_1), .B1 (b), .Y (n_3));
  INVX1 g106(.A (cin), .Y (n_2));
  INVX1 g107(.A (a), .Y (n_1));
  INVX1 g108(.A (b), .Y (n_0));
endmodule

module fag_60(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  XOR3X2 g131__4319(.A (b), .B (cin), .C (a), .Y (s));
  OAI21X4 g132__8428(.A0 (n_2), .A1 (n_0), .B0 (n_3), .Y (c));
  NAND2X1 g133__5526(.A (n_1), .B (b), .Y (n_3));
  NOR2X2 g134__6783(.A (n_1), .B (b), .Y (n_2));
  BUFX3 g135(.A (a), .Y (n_1));
  INVX1 g136(.A (cin), .Y (n_0));
endmodule

module fag_59(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X2 g195__3680(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  OAI2BB2X1 g196__1617(.A0N (cin), .A1N (n_0), .B0 (n_0), .B1 (cin), .Y
       (s));
  OAI21X2 g197__2802(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  INVX1 g200(.A (b), .Y (n_2));
  BUFX2 fopt(.A (a), .Y (n_1));
  XOR2X1 g2__1705(.A (n_1), .B (n_2), .Y (n_0));
endmodule

module fag_58(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_2;
  OAI2BB1X1 g115__5122(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  OAI21XL g117__8246(.A0 (a), .A1 (b), .B0 (cin), .Y (n_2));
  XOR3X2 g2(.A (a), .B (b), .C (cin), .Y (s));
endmodule

module fag_57(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  XOR3X2 g109__1881(.A (cin), .B (b), .C (a), .Y (s));
  OAI2BB1X1 g110__5115(.A0N (b), .A1N (a), .B0 (n_0), .Y (c));
  OAI21XL g111__7482(.A0 (a), .A1 (b), .B0 (cin), .Y (n_0));
endmodule

module fag_56(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  OAI2BB1X1 g104__4733(.A0N (b), .A1N (a), .B0 (n_0), .Y (c));
  XOR3X2 g105__6161(.A (b), .B (a), .C (cin), .Y (s));
  OAI21XL g106__9315(.A0 (a), .A1 (b), .B0 (cin), .Y (n_0));
endmodule

module fag_55(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X2 g173__9945(.A0N (b), .A1N (cin), .B0 (n_3), .Y (c));
  MXI2X1 g174__2883(.S0 (a), .B (n_1), .A (n_2), .Y (s));
  OAI21X2 g175__2346(.A0 (cin), .A1 (b), .B0 (a), .Y (n_3));
  INVX1 g176(.A (n_1), .Y (n_2));
  MXI2X1 g177__1666(.S0 (b), .B (cin), .A (n_0), .Y (n_1));
  INVX2 g178(.A (cin), .Y (n_0));
endmodule

module fag_54(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X1 g63__7410(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  MXI2X1 g64__6417(.S0 (n_1), .B (cin), .A (n_0), .Y (s));
  OAI21XL g65__5477(.A0 (a), .A1 (b), .B0 (cin), .Y (n_2));
  XOR2X1 g66__2398(.A (b), .B (a), .Y (n_1));
  INVX1 g67(.A (cin), .Y (n_0));
endmodule

module fag_53(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_2;
  OAI2BB1X1 g98__5107(.A0N (a), .A1N (b), .B0 (n_2), .Y (c));
  OAI21XL g99__6260(.A0 (b), .A1 (a), .B0 (cin), .Y (n_2));
  XNOR2X1 g2__4319(.A (n_0), .B (b), .Y (s));
  XNOR2X1 g103__8428(.A (cin), .B (a), .Y (n_0));
endmodule

module fag_52(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X4 g107__5526(.A0N (a), .A1N (b), .B0 (n_2), .Y (c));
  MXI2X1 g108__6783(.S0 (cin), .B (n_0), .A (n_1), .Y (s));
  OAI21X2 g109__3680(.A0 (b), .A1 (a), .B0 (cin), .Y (n_2));
  INVX1 g110(.A (n_0), .Y (n_1));
  XOR2X1 g111__1617(.A (a), .B (b), .Y (n_0));
endmodule

module fag_51(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g63__2802(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_50(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g107__1705(.A0N (a), .A1N (b), .B0 (n_1), .Y (c));
  OAI2BB2X4 g108__5122(.A0N (n_0), .A1N (cin), .B0 (cin), .B1 (n_0), .Y
       (s));
  OAI21X1 g109__8246(.A0 (b), .A1 (a), .B0 (cin), .Y (n_1));
  XNOR2X1 g110__7098(.A (b), .B (a), .Y (n_0));
endmodule

module fag_49(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X1 g63__6131(.A0N (b), .A1N (a), .B0 (n_2), .Y (c));
  MXI2X2 g64__1881(.S0 (cin), .B (n_0), .A (n_1), .Y (s));
  OAI21XL g65__5115(.A0 (a), .A1 (b), .B0 (cin), .Y (n_2));
  INVX1 g66(.A (n_0), .Y (n_1));
  XOR2X1 g67__7482(.A (a), .B (b), .Y (n_0));
endmodule

module left(p1, a, b);
  input [7:0] a, b;
  output [15:8] p1;
  wire [7:0] a, b;
  wire [15:8] p1;
  wire [41:23] s;
  wire [41:23] c;
  wire [5:0] n;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, z15, z22, z23, z29, z30, z31;
  wire z36, z37, z38, z39, z43, z44, z45, z46;
  wire z47, z50, z51, z52, z53, z54, z55, z57;
  wire z58, z59, z60, z61, z62, z63;
  hag_99 m1(s[23], c[23], z15, z22);
  fag_68 m2(s[25], c[25], s[23], z36, z29);
  hag_98 m3(s[31], c[31], s[25], z43);
  hag_97 m4(s[36], c[36], s[31], z50);
  hag_96 m5(p1[8], n[0], s[36], z57);
  hag_95 m6(s[24], c[24], z23, z30);
  fag_67 m7(s[26], c[26], s[24], c[23], z37);
  hag_94 m8(s[29], c[29], z44, z51);
  fag_66 m9(s[32], c[32], s[29], s[26], c[25]);
  fag_65 m10(s[37], c[37], s[32], c[31], z58);
  fag_64 m11(p1[9], n[1], s[37], c[36], n[0]);
  fag_63 m12(s[27], c[27], z38, z31, c[24]);
  fag_62 m13(s[30], c[30], z45, z52, z59);
  fag_61 m14(s[33], c[33], s[30], s[27], c[26]);
  fag_60 m15(s[38], c[38], s[33], c[29], c[32]);
  fag_59 m16(p1[10], n[2], s[38], c[37], n[1]);
  fag_58 m17(s[28], c[28], z39, z46, z53);
  fag_57 m18(s[34], c[34], s[28], c[27], z60);
  fag_56 m19(s[39], c[39], s[34], c[30], c[33]);
  fag_55 m20(p1[11], n[3], n[2], s[39], c[38]);
  fag_54 m21(s[35], c[35], z47, z54, c[28]);
  fag_53 m22(s[40], c[40], s[35], c[34], z61);
  fag_52 m23(p1[12], n[4], s[40], c[39], n[3]);
  fag_51 m24(s[41], c[41], z55, z62, c[35]);
  fag_50 m25(p1[13], n[5], s[41], c[40], n[4]);
  fag_49 m26(p1[14], p1[15], c[41], z63, n[5]);
  INVX4 g282(.A (n_9), .Y (z22));
  INVX4 g284(.A (n_8), .Y (z36));
  CLKINVX3 g285(.A (n_7), .Y (z30));
  CLKINVX3 g286(.A (n_6), .Y (z23));
  INVX4 g289(.A (n_5), .Y (z15));
  AND2X2 g291__4733(.A (a[6]), .B (b[7]), .Y (z62));
  AND2X2 g292__6161(.A (a[5]), .B (b[7]), .Y (z61));
  NAND2X2 g293__9315(.A (a[6]), .B (b[2]), .Y (n_9));
  NAND2X2 g295__9945(.A (a[4]), .B (b[4]), .Y (n_8));
  NAND2X4 g296__2883(.A (a[6]), .B (b[3]), .Y (n_7));
  NAND2X2 g297__2346(.A (a[7]), .B (b[2]), .Y (n_6));
  AND2X2 g299__1666(.A (a[1]), .B (b[7]), .Y (z57));
  AND2X2 g301__7410(.A (a[2]), .B (b[6]), .Y (z50));
  AND2X2 g302__6417(.A (a[3]), .B (b[5]), .Y (z43));
  NAND2X4 g303__5477(.A (a[7]), .B (b[1]), .Y (n_5));
  CLKINVX4 g306(.A (n_4), .Y (z29));
  INVX4 g307(.A (n_3), .Y (z52));
  INVX4 g308(.A (n_2), .Y (z31));
  INVX4 g309(.A (n_1), .Y (z45));
  INVX2 g311(.A (n_0), .Y (z38));
  NAND2X4 g315__2398(.A (a[5]), .B (b[3]), .Y (n_4));
  AND2X2 g316__5107(.A (a[7]), .B (b[7]), .Y (z63));
  NAND2X2 g317__6260(.A (a[4]), .B (b[6]), .Y (n_3));
  NAND2X4 g318__4319(.A (a[7]), .B (b[3]), .Y (n_2));
  NAND2X4 g319__8428(.A (a[5]), .B (b[5]), .Y (n_1));
  AND2X2 g320__5526(.A (a[7]), .B (b[6]), .Y (z55));
  NAND2X4 g322__6783(.A (a[6]), .B (b[4]), .Y (n_0));
  AND2X2 g323__3680(.A (a[2]), .B (b[7]), .Y (z58));
  AND2X2 g324__1617(.A (a[4]), .B (b[7]), .Y (z60));
  AND2X2 g326__2802(.A (a[6]), .B (b[6]), .Y (z54));
  AND2X2 g2__1705(.A (a[5]), .B (b[4]), .Y (z37));
  AND2X2 g327__5122(.A (a[5]), .B (b[6]), .Y (z53));
  AND2X4 g328__8246(.A (a[6]), .B (b[5]), .Y (z46));
  AND2X2 g329__7098(.A (a[7]), .B (b[4]), .Y (z39));
  AND2X2 g330__6131(.A (a[4]), .B (b[5]), .Y (z44));
  AND2X2 g331__1881(.A (a[3]), .B (b[7]), .Y (z59));
  AND2X2 g332__5115(.A (a[7]), .B (b[5]), .Y (z47));
  AND2X2 g333__7482(.A (a[3]), .B (b[6]), .Y (z51));
endmodule

module hag_93(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_1;
  NOR2X1 g26__4733(.A (c), .B (n_1), .Y (s));
  NOR2XL g27__6161(.A (b), .B (a), .Y (n_1));
  AND2X2 g2__9315(.A (b), .B (a), .Y (c));
endmodule

module fag_48(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  XOR3X2 g228__9945(.A (a), .B (cin), .C (b), .Y (s));
  OAI2BB1X2 g229__2883(.A0N (a), .A1N (b), .B0 (n_0), .Y (c));
  OAI21X1 g230__2346(.A0 (b), .A1 (a), .B0 (cin), .Y (n_0));
endmodule

module fag_47(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  OAI2BB1X4 g120__1666(.A0N (n_4), .A1N (cin), .B0 (n_3), .Y (c));
  OAI22XL g121__7410(.A0 (n_0), .A1 (n_6), .B0 (n_5), .B1 (cin), .Y
       (s));
  INVX1 g122(.A (n_5), .Y (n_6));
  AOI22X1 g123__6417(.A0 (n_1), .A1 (a), .B0 (b), .B1 (n_2), .Y (n_5));
  NAND2X1 g124__5477(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g125__2398(.A (b), .B (a), .Y (n_3));
  INVX1 g127(.A (a), .Y (n_2));
  INVX1 g128(.A (b), .Y (n_1));
  INVXL fopt(.A (cin), .Y (n_0));
endmodule

module rca3bit(s, c, a, b);
  input [2:0] a, b;
  output [2:0] s;
  output c;
  wire [2:0] a, b;
  wire [2:0] s;
  wire c;
  wire c0, c1;
  hag_93 a1(s[0], c0, a[0], b[0]);
  fag_48 a2(s[1], c1, a[1], b[1], c0);
  fag_47 a3(s[2], c, a[2], b[2], c1);
endmodule

module bec5bit(s, a, b, c, d, e);
  input a, b, c, d, e;
  output [4:0] s;
  wire a, b, c, d, e;
  wire [4:0] s;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9;
  MXI2X1 g208__5107(.S0 (n_1), .B (n_3), .A (e), .Y (s[4]));
  OAI22XL g209__6260(.A0 (d), .A1 (n_8), .B0 (n_2), .B1 (n_0), .Y
       (s[3]));
  NOR2BXL g212__4319(.AN (n_8), .B (n_9), .Y (s[2]));
  NOR2X1 g213__8428(.A (n_7), .B (c), .Y (n_9));
  NAND2X2 g214__5526(.A (n_7), .B (c), .Y (n_8));
  CLKINVX3 g215(.A (n_4), .Y (n_7));
  INVX1 g216(.A (n_5), .Y (s[1]));
  OAI21XL g217__6783(.A0 (b), .A1 (a), .B0 (n_4), .Y (n_5));
  NAND2X1 g218__3680(.A (b), .B (a), .Y (n_4));
  INVX1 g219(.A (e), .Y (n_3));
  INVX1 g220(.A (d), .Y (n_2));
  NAND2BX2 g2__1617(.AN (n_8), .B (d), .Y (n_1));
  INVXL g221(.A (n_8), .Y (n_0));
endmodule

module dadda(p, a, b, clk);
  input [7:0] a, b;
  input clk;
  output [15:0] p;
  wire [7:0] a, b;
  wire clk;
  wire [15:0] p;
  wire [10:0] w112;
  wire [15:0] z;
  wire [15:8] w113;
  wire [15:11] w2;
  wire UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6,
       UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, n_0, n_1, n_2, n_3,
       n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, w1;
  right_da a1({w112[10:3], z[2:0]}, a, b);
  left a2(w113, {a[7:1], UNCONNECTED_HIER_Z}, {b[7:1],
       UNCONNECTED_HIER_Z0});
  rca3bit x1(z[10:8], w1, w113[10:8], w112[10:8]);
  bec5bit x2({w2[15:12], UNCONNECTED3}, w113[11], w113[12], w113[13],
       w113[14], w113[15]);
  CLKBUFX20 g124(.A (n_23), .Y (p[15]));
  CLKBUFX20 g125(.A (n_22), .Y (p[14]));
  DFFX4 \p_reg[15] (.CK (clk), .D (n_6), .Q (n_23), .QN (UNCONNECTED4));
  DFFX4 \p_reg[14] (.CK (clk), .D (n_7), .Q (n_22), .QN (UNCONNECTED5));
  CLKBUFX20 g128(.A (n_20), .Y (p[12]));
  CLKBUFX20 g129(.A (n_21), .Y (p[13]));
  CLKBUFX20 g130(.A (n_19), .Y (p[11]));
  SDFFHQX4 \p_reg[12] (.CK (clk), .D (w2[12]), .SI (w113[12]), .SE
       (n_1), .Q (n_20));
  SDFFHQX4 \p_reg[11] (.CK (clk), .D (w113[11]), .SI (n_2), .SE (w1),
       .Q (n_19));
  OAI21X1 g134__2802(.A0 (w1), .A1 (n_3), .B0 (n_5), .Y (n_7));
  OAI21X1 g135__1705(.A0 (w1), .A1 (n_0), .B0 (n_4), .Y (n_6));
  CLKBUFX20 g136(.A (n_16), .Y (p[8]));
  CLKBUFX16 g137(.A (n_8), .Y (p[0]));
  CLKBUFX20 g138(.A (n_15), .Y (p[7]));
  CLKBUFX20 g139(.A (n_14), .Y (p[6]));
  CLKBUFX16 g140(.A (n_13), .Y (p[5]));
  CLKBUFX20 g141(.A (n_18), .Y (p[10]));
  DFFX4 \p_reg[8] (.CK (clk), .D (z[8]), .Q (n_16), .QN (UNCONNECTED6));
  DFFHQX4 \p_reg[0] (.CK (clk), .D (z[0]), .Q (n_8));
  DFFX4 \p_reg[7] (.CK (clk), .D (w112[7]), .Q (n_15), .QN
       (UNCONNECTED7));
  DFFX4 \p_reg[6] (.CK (clk), .D (w112[6]), .Q (n_14), .QN
       (UNCONNECTED8));
  DFFHQX4 \p_reg[5] (.CK (clk), .D (w112[5]), .Q (n_13));
  DFFX4 \p_reg[10] (.CK (clk), .D (z[10]), .Q (n_18), .QN
       (UNCONNECTED9));
  CLKBUFX16 g148(.A (n_11), .Y (p[3]));
  CLKBUFX20 g149(.A (n_17), .Y (p[9]));
  CLKBUFX16 g150(.A (n_10), .Y (p[2]));
  CLKBUFX16 g151(.A (n_9), .Y (p[1]));
  CLKBUFX16 g152(.A (n_12), .Y (p[4]));
  NAND2X1 g153__5122(.A (w1), .B (w2[14]), .Y (n_5));
  DFFHQX4 \p_reg[3] (.CK (clk), .D (w112[3]), .Q (n_11));
  DFFX4 \p_reg[9] (.CK (clk), .D (z[9]), .Q (n_17), .QN
       (UNCONNECTED10));
  DFFHQX4 \p_reg[2] (.CK (clk), .D (z[2]), .Q (n_10));
  DFFHQX4 \p_reg[1] (.CK (clk), .D (z[1]), .Q (n_9));
  NAND2X1 g158__8246(.A (w2[15]), .B (w1), .Y (n_4));
  DFFHQX4 \p_reg[4] (.CK (clk), .D (w112[4]), .Q (n_12));
  INVX1 g160(.A (w113[14]), .Y (n_3));
  INVX1 g161(.A (w113[11]), .Y (n_2));
  INVX2 g162(.A (w1), .Y (n_1));
  INVX1 g163(.A (w113[15]), .Y (n_0));
  SDFFHQX4 \p_reg[13] (.CK (clk), .D (w2[13]), .SI (w113[13]), .SE
       (n_1), .Q (n_21));
endmodule

