
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jul  5 2024 13:50:52 IST (Jul  5 2024 08:20:52 UTC)

// Verification Directory fv/dadda 

module hag(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0;
  CLKINVX3 g20(.A (n_0), .Y (c));
  AOI2BB1XL g21(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  NAND2X2 g23(.A (b), .B (a), .Y (n_0));
endmodule

module hag_105(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  CMPR22X1 g22(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB2XL g171(.A0N (cin), .A1N (n_0), .B0 (n_0), .B1 (cin), .Y (s));
  OAI2BB1X2 g172(.A0N (b), .A1N (cin), .B0 (n_1), .Y (c));
  OAI21X1 g173(.A0 (cin), .A1 (b), .B0 (a), .Y (n_1));
  XNOR2X1 g174(.A (a), .B (b), .Y (n_0));
endmodule

module hag_104(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_1;
  MXI2X1 g23(.S0 (b), .B (a), .A (n_1), .Y (s));
  INVX1 g25(.A (a), .Y (n_1));
  AND2X2 g2(.A (b), .B (a), .Y (c));
endmodule

module fag_92(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X2 g59(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X2 g60(.S0 (cin), .B (n_1), .A (n_2), .Y (s));
  OAI21XL g61(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  INVX1 g62(.A (n_1), .Y (n_2));
  MXI2X1 g63(.S0 (a), .B (b), .A (n_0), .Y (n_1));
  INVX4 g64(.A (b), .Y (n_0));
endmodule

module fag_91(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire UNCONNECTED, n_0, n_1;
  OAI2BB1X1 g173(.A0N (b), .A1N (cin), .B0 (n_1), .Y (c));
  OAI21X1 g175(.A0 (cin), .A1 (b), .B0 (a), .Y (n_1));
  XOR2X1 g176(.A (cin), .B (b), .Y (n_0));
  ADDHX1 g178(.A (a), .B (n_0), .S (s), .CO (UNCONNECTED));
endmodule

module hag_103(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g26(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_90(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X2 g97(.A0N (n_0), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X4 g98(.S0 (n_4), .B (a), .A (n_2), .Y (s));
  MXI2X4 g99(.S0 (b), .B (cin), .A (n_1), .Y (n_4));
  NAND2X1 g101(.A (b), .B (cin), .Y (n_3));
  INVX2 g102(.A (a), .Y (n_2));
  CLKINVX3 g104(.A (cin), .Y (n_1));
  NAND2BXL g2(.AN (b), .B (n_1), .Y (n_0));
endmodule

module fag_89(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  MXI2X2 g61(.S0 (a), .B (n_5), .A (n_4), .Y (s));
  OAI21X2 g62(.A0 (n_2), .A1 (n_1), .B0 (n_3), .Y (c));
  INVX1 g63(.A (n_4), .Y (n_5));
  MXI2X2 g64(.S0 (cin), .B (n_0), .A (b), .Y (n_4));
  NAND2X1 g65(.A (a), .B (b), .Y (n_3));
  NOR2X1 g66(.A (a), .B (b), .Y (n_2));
  INVX1 g67(.A (cin), .Y (n_1));
  INVX1 g68(.A (b), .Y (n_0));
endmodule

module fag_88(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_3, n_4;
  OAI21X2 g108(.A0 (n_4), .A1 (n_1), .B0 (n_3), .Y (c));
  NOR2X2 g112(.A (a), .B (b), .Y (n_4));
  NAND2X1 g113(.A (a), .B (b), .Y (n_3));
  INVX1 g116(.A (cin), .Y (n_1));
  XNOR3X2 g118(.A (b), .B (a), .C (n_1), .Y (s));
endmodule

module fag_87(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI21X2 g97(.A0 (n_1), .A1 (n_3), .B0 (n_2), .Y (c));
  MXI2X4 g98(.S0 (n_4), .B (cin), .A (n_1), .Y (s));
  MXI2X2 g99(.S0 (a), .B (b), .A (n_0), .Y (n_4));
  NOR2X2 g100(.A (a), .B (b), .Y (n_3));
  NAND2X1 g101(.A (b), .B (a), .Y (n_2));
  CLKINVX3 g102(.A (cin), .Y (n_1));
  CLKINVX3 g103(.A (b), .Y (n_0));
endmodule

module fag_86(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X2 g115(.A0N (b), .A1N (cin), .B0 (n_3), .Y (c));
  MXI2X2 g116(.S0 (n_2), .B (a), .A (n_1), .Y (s));
  OAI21X1 g117(.A0 (cin), .A1 (b), .B0 (a), .Y (n_3));
  MXI2X2 g118(.S0 (b), .B (cin), .A (n_0), .Y (n_2));
  INVX4 g119(.A (a), .Y (n_1));
  CLKINVX3 g120(.A (cin), .Y (n_0));
endmodule

module hag_102(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g22(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_85(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  XNOR3X2 g77(.A (cin), .B (n_1), .C (a), .Y (s));
  OAI22X1 g78(.A0 (n_0), .A1 (n_2), .B0 (n_3), .B1 (n_1), .Y (c));
  INVX1 g80(.A (a), .Y (n_3));
  INVX1 g81(.A (cin), .Y (n_2));
  CLKINVX3 g84(.A (b), .Y (n_1));
  NOR2BXL g2(.AN (n_1), .B (a), .Y (n_0));
endmodule

module fag_84(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1;
  XOR3X2 g114(.A (b), .B (cin), .C (a), .Y (s));
  OAI2BB1X2 g115(.A0N (b), .A1N (a), .B0 (n_1), .Y (c));
  OAI21X2 g116(.A0 (a), .A1 (b), .B0 (cin), .Y (n_1));
endmodule

module hag_101(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g22(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_83(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire UNCONNECTED0, n_0, n_2, n_4, n_5;
  OAI2BB1X2 g59(.A0N (n_4), .A1N (cin), .B0 (n_0), .Y (c));
  MXI2X2 g61(.S0 (a), .B (b), .A (n_2), .Y (n_5));
  NAND2BX1 g62(.AN (a), .B (n_2), .Y (n_4));
  CLKINVX3 g67(.A (b), .Y (n_2));
  NAND2BX1 g68(.AN (n_2), .B (a), .Y (n_0));
  CMPR22X1 g70(.A (n_5), .B (cin), .S (s), .CO (UNCONNECTED0));
endmodule

module fag_82(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X1 g79(.A0N (b), .A1N (a), .B0 (n_4), .Y (c));
  MXI2X4 g80(.S0 (n_3), .B (cin), .A (n_2), .Y (s));
  OAI21XL g81(.A0 (a), .A1 (b), .B0 (cin), .Y (n_4));
  OAI2BB1X4 g82(.A0N (a), .A1N (n_1), .B0 (n_0), .Y (n_3));
  INVX1 g84(.A (cin), .Y (n_2));
  INVX1 g86(.A (b), .Y (n_1));
  NAND2BX2 g2(.AN (a), .B (b), .Y (n_0));
endmodule

module fag_81(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  XOR3X4 g77(.A (cin), .B (a), .C (b), .Y (s));
  OAI21X2 g78(.A0 (n_2), .A1 (n_1), .B0 (n_3), .Y (c));
  NAND2X1 g79(.A (b), .B (a), .Y (n_3));
  NOR2X2 g80(.A (b), .B (a), .Y (n_2));
  INVX1 g81(.A (n_0), .Y (n_1));
  CLKBUFXL drc_bufs84(.A (cin), .Y (n_0));
endmodule

module fag_80(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  XNOR3X2 g77(.A (n_2), .B (b), .C (a), .Y (s));
  OAI21X4 g78(.A0 (n_4), .A1 (n_2), .B0 (n_5), .Y (c));
  NAND2X2 g79(.A (n_3), .B (n_1), .Y (n_5));
  NOR2X4 g80(.A (n_3), .B (n_1), .Y (n_4));
  BUFX3 g81(.A (a), .Y (n_3));
  INVX1 g82(.A (cin), .Y (n_2));
  INVX1 g83(.A (n_0), .Y (n_1));
  INVX1 g85(.A (b), .Y (n_0));
endmodule

module fag_79(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_3, n_4;
  OAI2BB1X1 g52(.A0N (b), .A1N (a), .B0 (n_4), .Y (c));
  OAI21X1 g54(.A0 (a), .A1 (b), .B0 (cin), .Y (n_4));
  MXI2X1 g56(.S0 (b), .B (n_1), .A (a), .Y (n_3));
  INVX1 g59(.A (a), .Y (n_1));
  XNOR2X1 g2(.A (n_3), .B (cin), .Y (s));
endmodule

module fag_78(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_3, n_16, n_17;
  OAI21X2 g79(.A0 (n_3), .A1 (n_1), .B0 (n_16), .Y (c));
  MXI2X2 g80(.S0 (n_17), .B (cin), .A (n_1), .Y (s));
  NOR2X1 g82(.A (a), .B (b), .Y (n_3));
  CLKINVX3 g84(.A (cin), .Y (n_1));
  AHHCONX2 g2(.A (b), .CI (a), .S (n_17), .CON (n_16));
endmodule

module hag_100(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g22(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_77(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_2, n_4, n_10;
  OAI2BB1X1 g79(.A0N (b), .A1N (a), .B0 (n_4), .Y (c));
  MXI2X2 g80(.S0 (n_10), .B (cin), .A (n_2), .Y (s));
  OAI21XL g81(.A0 (a), .A1 (b), .B0 (cin), .Y (n_4));
  INVX1 g84(.A (cin), .Y (n_2));
  XOR2X2 g87(.A (a), .B (b), .Y (n_10));
endmodule

module fag_76(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X2 g97(.A0N (cin), .A1N (b), .B0 (n_2), .Y (c));
  MXI2X2 g98(.S0 (n_0), .B (a), .A (n_1), .Y (s));
  OAI21X1 g99(.A0 (b), .A1 (cin), .B0 (a), .Y (n_2));
  INVX2 g101(.A (a), .Y (n_1));
  XOR2X4 g2(.A (cin), .B (b), .Y (n_0));
endmodule

module fag_75(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_3;
  INVX1 g41(.A (n_3), .Y (c));
  AOI22XL g42(.A0 (cin), .A1 (n_0), .B0 (a), .B1 (b), .Y (n_3));
  MXI2X2 g43(.S0 (n_0), .B (cin), .A (n_1), .Y (s));
  INVX1 g46(.A (cin), .Y (n_1));
  XOR2X1 g2(.A (b), .B (a), .Y (n_0));
endmodule

module fag_74(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire UNCONNECTED1, n_0, n_1, n_2;
  OAI2BB1X2 g82(.A0N (cin), .A1N (b), .B0 (n_2), .Y (c));
  MXI2X2 g83(.S0 (n_0), .B (n_1), .A (a), .Y (s));
  OAI21XL g84(.A0 (b), .A1 (cin), .B0 (a), .Y (n_2));
  CLKINVX3 g86(.A (a), .Y (n_1));
  AHHCINX2 g89(.A (cin), .CIN (b), .S (n_0), .CO (UNCONNECTED1));
endmodule

module fag_73(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  MXI2X2 g77(.S0 (n_6), .B (n_3), .A (a), .Y (s));
  OAI21X2 g78(.A0 (n_4), .A1 (n_2), .B0 (n_5), .Y (c));
  MXI2X2 g79(.S0 (b), .B (n_2), .A (cin), .Y (n_6));
  NAND2X1 g80(.A (a), .B (n_1), .Y (n_5));
  NOR2X2 g81(.A (a), .B (n_1), .Y (n_4));
  INVX1 g82(.A (a), .Y (n_3));
  INVX1 g83(.A (cin), .Y (n_2));
  CLKINVX2 g84(.A (n_0), .Y (n_1));
  INVX1 g86(.A (b), .Y (n_0));
endmodule

module fag_72(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire UNCONNECTED2, n_1, n_2, n_3, n_4, n_5, n_6;
  OAI2BB1X4 g52(.A0N (n_5), .A1N (cin), .B0 (n_4), .Y (c));
  MXI2X1 g55(.S0 (b), .B (n_2), .A (a), .Y (n_6));
  NAND2X1 g56(.A (n_2), .B (n_1), .Y (n_5));
  NAND2X1 g57(.A (a), .B (b), .Y (n_4));
  INVX1 g59(.A (cin), .Y (n_3));
  CLKINVX3 g60(.A (a), .Y (n_2));
  INVX2 g61(.A (b), .Y (n_1));
  ADDHX1 g64(.A (n_6), .B (n_3), .S (s), .CO (UNCONNECTED2));
endmodule

module fag_71(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  XOR3X2 g77(.A (cin), .B (a), .C (b), .Y (s));
  OAI2BB1X1 g78(.A0N (b), .A1N (a), .B0 (n_0), .Y (c));
  OAI21XL g79(.A0 (b), .A1 (a), .B0 (cin), .Y (n_0));
endmodule

module fag_70(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_3, n_4;
  OAI2BB1X2 g47(.A0N (b), .A1N (a), .B0 (n_4), .Y (c));
  MXI2X2 g48(.S0 (cin), .B (n_1), .A (n_3), .Y (s));
  NAND2X2 g49(.A (cin), .B (n_1), .Y (n_4));
  INVX1 g50(.A (n_1), .Y (n_3));
  MXI2X2 g52(.S0 (a), .B (b), .A (n_0), .Y (n_1));
  CLKINVX3 g53(.A (b), .Y (n_0));
endmodule

module fag_69(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X2 g41(.A0N (n_2), .A1N (cin), .B0 (n_1), .Y (c));
  OAI2BB2X2 g42(.A0N (n_0), .A1N (cin), .B0 (cin), .B1 (n_0), .Y (s));
  INVX1 g43(.A (n_0), .Y (n_2));
  NAND2X1 g45(.A (b), .B (a), .Y (n_1));
  XNOR2X1 g2(.A (b), .B (a), .Y (n_0));
endmodule

module right_da(p, a, b);
  input [7:0] a, b;
  output [10:0] p;
  wire [7:0] a, b;
  wire [10:0] p;
  wire [56:1] d;
  wire [7:0] l;
  wire [22:0] s;
  wire [22:0] c;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_63;
  hag r1(p[1], l[0], d[1], d[8]);
  hag_105 r2(s[16], c[16], d[2], d[9]);
  fag r3(p[2], l[1], s[16], d[16], l[0]);
  hag_104 r4(s[10], c[10], d[3], d[10]);
  fag_92 r5(s[17], c[17], d[17], d[24], s[10]);
  fag_91 r6(p[3], l[2], s[17], c[16], l[1]);
  hag_103 r7(s[3], c[3], d[4], d[11]);
  fag_90 r8(s[11], c[11], s[3], d[18], d[25]);
  fag_89 r9(s[18], c[18], s[11], d[32], c[10]);
  fag_88 r10(p[4], l[3], s[18], c[17], l[2]);
  fag_87 r11(s[4], c[4], d[5], d[12], d[19]);
  fag_86 r12(s[12], c[12], s[4], c[3], s[7]);
  hag_102 r13(s[7], c[7], d[26], d[33]);
  fag_85 r14(s[19], c[19], s[12], c[11], d[40]);
  fag_84 r15(p[5], l[4], s[19], c[18], l[3]);
  hag_101 r16(s[0], c[0], d[6], d[13]);
  fag_83 r17(s[5], c[5], n_63, d[27], s[0]);
  fag_82 r18(s[8], c[8], d[34], d[41], d[48]);
  fag_81 r19(s[13], c[13], s[8], s[5], c[4]);
  fag_80 r20(s[20], c[20], s[13], c[12], c[7]);
  fag_79 r21(p[6], l[5], s[20], c[19], l[4]);
  fag_78 r22(s[1], c[1], d[7], d[14], d[21]);
  hag_100 r23(s[2], c[2], d[28], d[35]);
  fag_77 r24(s[9], c[9], d[42], d[49], d[56]);
  fag_76 r25(s[6], c[6], s[1], s[2], c[0]);
  fag_75 r26(s[15], c[15], c[1], c[2], c[6]);
  fag_74 r27(s[14], c[14], s[6], c[5], s[9]);
  fag_73 r28(s[21], c[21], s[14], c[13], c[8]);
  fag_72 r29(p[7], l[6], s[21], c[20], l[5]);
  fag_71 r30(s[22], c[22], s[15], c[14], c[9]);
  fag_70 r31(p[8], l[7], s[22], c[21], l[6]);
  fag_69 r32(p[9], p[10], c[15], c[22], l[7]);
  INVX4 g253(.A (n_19), .Y (d[14]));
  INVX2 g254(.A (n_18), .Y (d[1]));
  CLKINVX3 g257(.A (n_17), .Y (d[17]));
  CLKINVX3 g258(.A (n_16), .Y (d[42]));
  INVX4 g261(.A (n_15), .Y (d[24]));
  CLKINVX3 g262(.A (n_14), .Y (d[6]));
  INVX4 g263(.A (n_13), .Y (d[4]));
  INVX2 g265(.A (n_12), .Y (d[13]));
  CLKINVX3 g267(.A (n_10), .Y (d[27]));
  INVX2 g268(.A (n_9), .Y (d[34]));
  NAND2X4 g269(.A (a[6]), .B (b[1]), .Y (n_19));
  NAND2X4 g270(.A (a[1]), .B (b[0]), .Y (n_18));
  NAND2X2 g273(.A (a[1]), .B (b[2]), .Y (n_17));
  NAND2X2 g274(.A (a[2]), .B (b[5]), .Y (n_16));
  AND2X2 g275(.A (a[0]), .B (b[5]), .Y (d[40]));
  AND2X2 g278(.A (a[0]), .B (b[0]), .Y (p[0]));
  NAND2X4 g279(.A (a[0]), .B (b[3]), .Y (n_15));
  NAND2X2 g280(.A (a[6]), .B (b[0]), .Y (n_14));
  NAND2X4 g281(.A (a[4]), .B (b[0]), .Y (n_13));
  NAND2X2 g283(.A (a[5]), .B (b[1]), .Y (n_12));
  NAND2X2 g285(.A (a[3]), .B (b[3]), .Y (n_10));
  NAND2X2 g286(.A (a[2]), .B (b[4]), .Y (n_9));
  CLKINVX3 g287(.A (n_8), .Y (d[8]));
  INVX4 g288(.A (n_7), .Y (d[11]));
  INVX3 g289(.A (n_6), .Y (d[41]));
  INVX4 g290(.A (n_5), .Y (d[7]));
  CLKINVX3 g297(.A (n_4), .Y (d[3]));
  CLKINVX3 g299(.A (n_3), .Y (d[35]));
  CLKINVX3 g300(.A (n_2), .Y (d[49]));
  INVX2 g301(.A (n_1), .Y (d[5]));
  INVX4 g303(.A (n_0), .Y (d[12]));
  NAND2X4 g305(.A (a[0]), .B (b[1]), .Y (n_8));
  NAND2X2 g306(.A (a[3]), .B (b[1]), .Y (n_7));
  NAND2X2 g307(.A (a[1]), .B (b[5]), .Y (n_6));
  NAND2X2 g308(.A (a[7]), .B (b[0]), .Y (n_5));
  NAND2X4 g315(.A (a[3]), .B (b[0]), .Y (n_4));
  NAND2X2 g317(.A (a[3]), .B (b[4]), .Y (n_3));
  NAND2X4 g318(.A (a[1]), .B (b[6]), .Y (n_2));
  NAND2X2 g319(.A (a[5]), .B (b[0]), .Y (n_1));
  NAND2X4 g321(.A (a[4]), .B (b[1]), .Y (n_0));
  AND2X2 g2(.A (a[2]), .B (b[0]), .Y (d[2]));
  AND2X2 g323(.A (a[0]), .B (b[7]), .Y (d[56]));
  AND2X2 g324(.A (a[4]), .B (b[3]), .Y (d[28]));
  AND2X4 g325(.A (a[5]), .B (b[2]), .Y (d[21]));
  AND2X4 g326(.A (a[0]), .B (b[6]), .Y (d[48]));
  AND2X2 g327(.A (a[0]), .B (b[2]), .Y (d[16]));
  AND2X4 g328(.A (a[1]), .B (b[4]), .Y (d[33]));
  AND2X2 g329(.A (a[2]), .B (b[2]), .Y (d[18]));
  AND2X4 g330(.A (a[3]), .B (b[2]), .Y (d[19]));
  AND2X4 g331(.A (a[1]), .B (b[3]), .Y (d[25]));
  AND2X4 g332(.A (a[1]), .B (b[1]), .Y (d[9]));
  AND2X4 g333(.A (a[0]), .B (b[4]), .Y (d[32]));
  AND2X2 g334(.A (a[2]), .B (b[1]), .Y (d[10]));
  AND2X2 g335(.A (a[2]), .B (b[3]), .Y (d[26]));
  AND2X2 g352(.A (a[4]), .B (b[2]), .Y (n_63));
endmodule

module hag_99(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0, n_1;
  INVX4 g22(.A (n_1), .Y (c));
  MXI2X4 g23(.S0 (b), .B (a), .A (n_0), .Y (s));
  NAND2X2 g24(.A (b), .B (a), .Y (n_1));
  INVX4 g25(.A (a), .Y (n_0));
endmodule

module fag_68(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X2 g120(.A0N (cin), .A1N (b), .B0 (n_4), .Y (c));
  MXI2X4 g121(.S0 (n_3), .B (a), .A (n_2), .Y (s));
  OAI21X1 g122(.A0 (b), .A1 (cin), .B0 (a), .Y (n_4));
  OAI2BB1X2 g123(.A0N (b), .A1N (n_1), .B0 (n_0), .Y (n_3));
  CLKINVX3 g125(.A (a), .Y (n_2));
  INVX1 g127(.A (cin), .Y (n_1));
  NAND2BX2 g2(.AN (b), .B (cin), .Y (n_0));
endmodule

module hag_98(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0, n_1, n_2;
  INVX4 g22(.A (n_2), .Y (c));
  AOI22X2 g23(.A0 (n_0), .A1 (n_1), .B0 (a), .B1 (b), .Y (s));
  NAND2X2 g24(.A (a), .B (b), .Y (n_2));
  INVX1 g25(.A (b), .Y (n_1));
  INVX2 g26(.A (a), .Y (n_0));
endmodule

module hag_97(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHX2 g22(.A (b), .B (a), .S (s), .CO (c));
endmodule

module hag_96(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0;
  INVX4 g20(.A (n_0), .Y (c));
  AOI2BB1X1 g21(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  NAND2X2 g23(.A (a), .B (b), .Y (n_0));
endmodule

module hag_95(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_1;
  INVX2 g22(.A (n_1), .Y (c));
  NAND2X2 g24(.A (b), .B (a), .Y (n_1));
  XOR2X4 g2(.A (b), .B (a), .Y (s));
endmodule

module fag_67(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_2, n_3;
  OAI21X2 g78(.A0 (n_2), .A1 (n_1), .B0 (n_3), .Y (c));
  NAND2X1 g79(.A (a), .B (b), .Y (n_3));
  NOR2X2 g80(.A (a), .B (b), .Y (n_2));
  INVX1 g81(.A (cin), .Y (n_1));
  XOR3X4 g2(.A (cin), .B (b), .C (a), .Y (s));
endmodule

module hag_94(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  CMPR22X1 g20(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_66(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_4;
  OAI2BB1X2 g106(.A0N (a), .A1N (cin), .B0 (n_4), .Y (c));
  OAI21X1 g108(.A0 (cin), .A1 (a), .B0 (b), .Y (n_4));
  XOR3X2 g114(.A (a), .B (cin), .C (b), .Y (s));
endmodule

module fag_65(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X1 g94(.A0N (cin), .A1N (b), .B0 (n_3), .Y (c));
  MXI2X2 g95(.S0 (n_2), .B (a), .A (n_1), .Y (s));
  OAI21XL g96(.A0 (b), .A1 (cin), .B0 (a), .Y (n_3));
  MXI2X2 g97(.S0 (cin), .B (b), .A (n_0), .Y (n_2));
  INVX2 g98(.A (a), .Y (n_1));
  INVX2 g99(.A (b), .Y (n_0));
endmodule

module fag_64(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1;
  OAI2BB1X2 g173(.A0N (b), .A1N (cin), .B0 (n_1), .Y (c));
  OAI2BB2X1 g174(.A0N (a), .A1N (n_0), .B0 (n_0), .B1 (a), .Y (s));
  OAI21X2 g175(.A0 (cin), .A1 (b), .B0 (a), .Y (n_1));
  XNOR2X1 g2(.A (cin), .B (b), .Y (n_0));
endmodule

module fag_63(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X1 g71(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X2 g72(.S0 (n_2), .B (cin), .A (n_1), .Y (s));
  OAI21XL g73(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  MXI2X2 g74(.S0 (a), .B (b), .A (n_0), .Y (n_2));
  CLKINVX3 g75(.A (cin), .Y (n_1));
  CLKINVX3 g76(.A (b), .Y (n_0));
endmodule

module fag_62(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X1 g79(.A0N (b), .A1N (a), .B0 (n_4), .Y (c));
  MXI2X4 g80(.S0 (n_3), .B (cin), .A (n_2), .Y (s));
  OAI21XL g81(.A0 (a), .A1 (b), .B0 (cin), .Y (n_4));
  OAI2BB1X4 g82(.A0N (a), .A1N (n_1), .B0 (n_0), .Y (n_3));
  INVX1 g84(.A (cin), .Y (n_2));
  INVX1 g86(.A (b), .Y (n_1));
  NAND2BX2 g2(.AN (a), .B (b), .Y (n_0));
endmodule

module fag_61(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X1 g71(.A0N (a), .A1N (b), .B0 (n_4), .Y (c));
  MXI2X4 g72(.S0 (n_3), .B (cin), .A (n_2), .Y (s));
  OAI21XL g73(.A0 (b), .A1 (a), .B0 (cin), .Y (n_4));
  OAI2BB1X4 g74(.A0N (a), .A1N (n_1), .B0 (n_0), .Y (n_3));
  INVX1 g76(.A (cin), .Y (n_2));
  INVX1 g78(.A (b), .Y (n_1));
  NAND2BX4 g2(.AN (a), .B (b), .Y (n_0));
endmodule

module fag_60(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  XOR3X4 g86(.A (b), .B (cin), .C (a), .Y (s));
  OAI21X2 g87(.A0 (n_1), .A1 (n_0), .B0 (n_2), .Y (c));
  NAND2X1 g88(.A (a), .B (b), .Y (n_2));
  NOR2X1 g89(.A (a), .B (b), .Y (n_1));
  INVX1 g90(.A (cin), .Y (n_0));
endmodule

module fag_59(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_4;
  OAI2BB1X2 g108(.A0N (b), .A1N (a), .B0 (n_4), .Y (c));
  OAI2BB2X1 g109(.A0N (n_2), .A1N (n_0), .B0 (n_0), .B1 (n_2), .Y (s));
  OAI21X2 g110(.A0 (a), .A1 (b), .B0 (cin), .Y (n_4));
  INVX1 fopt(.A (n_1), .Y (n_2));
  INVX1 fopt121(.A (cin), .Y (n_1));
  XNOR2X1 g2(.A (a), .B (b), .Y (n_0));
endmodule

module fag_58(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3;
  OAI2BB1X1 g67(.A0N (b), .A1N (a), .B0 (n_3), .Y (c));
  MXI2X2 g68(.S0 (n_2), .B (cin), .A (n_1), .Y (s));
  OAI21XL g69(.A0 (a), .A1 (b), .B0 (cin), .Y (n_3));
  MXI2X1 g70(.S0 (a), .B (b), .A (n_0), .Y (n_2));
  INVX1 g71(.A (cin), .Y (n_1));
  CLKINVX3 g72(.A (b), .Y (n_0));
endmodule

module fag_57(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  XOR3X4 g77(.A (cin), .B (a), .C (b), .Y (s));
  OAI2BB1X1 g78(.A0N (b), .A1N (a), .B0 (n_0), .Y (c));
  OAI21XL g79(.A0 (a), .A1 (b), .B0 (cin), .Y (n_0));
endmodule

module fag_56(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  OAI2BB1X1 g59(.A0N (b), .A1N (a), .B0 (n_0), .Y (c));
  XOR3X2 g60(.A (b), .B (a), .C (cin), .Y (s));
  OAI21XL g61(.A0 (a), .A1 (b), .B0 (cin), .Y (n_0));
endmodule

module fag_55(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4;
  OAI2BB1X2 g119(.A0N (b), .A1N (cin), .B0 (n_4), .Y (c));
  MXI2X1 g120(.S0 (a), .B (n_3), .A (n_2), .Y (s));
  OAI21X1 g121(.A0 (cin), .A1 (b), .B0 (a), .Y (n_4));
  INVX2 g122(.A (n_2), .Y (n_3));
  AOI22X1 g123(.A0 (n_0), .A1 (b), .B0 (n_1), .B1 (cin), .Y (n_2));
  INVX1 g124(.A (b), .Y (n_1));
  INVX1 g125(.A (cin), .Y (n_0));
endmodule

module fag_54(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_1, n_2, n_3;
  INVX1 g41(.A (n_3), .Y (c));
  AOI22X1 g42(.A0 (cin), .A1 (n_2), .B0 (b), .B1 (a), .Y (n_3));
  MXI2X1 g45(.S0 (a), .B (b), .A (n_1), .Y (n_2));
  INVX1 g46(.A (b), .Y (n_1));
  XOR2X1 g2(.A (cin), .B (n_2), .Y (s));
endmodule

module fag_53(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB2X1 g65(.A0N (b), .A1N (n_1), .B0 (n_1), .B1 (b), .Y (s));
  OAI2BB1X1 g66(.A0N (a), .A1N (b), .B0 (n_2), .Y (c));
  OAI21XL g67(.A0 (b), .A1 (a), .B0 (cin), .Y (n_2));
  MXI2X1 g68(.S0 (cin), .B (n_0), .A (a), .Y (n_1));
  INVX1 g69(.A (a), .Y (n_0));
endmodule

module fag_52(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_2, n_8, n_9;
  OAI2BB1X4 g47(.A0N (n_8), .A1N (cin), .B0 (n_9), .Y (c));
  MXI2X1 g48(.S0 (cin), .B (n_8), .A (n_2), .Y (s));
  INVX1 g49(.A (n_8), .Y (n_2));
  AHHCONX2 g53(.A (a), .CI (b), .S (n_8), .CON (n_9));
endmodule

module fag_51(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_2;
  INVX1 g41(.A (n_2), .Y (c));
  AOI22X1 g42(.A0 (cin), .A1 (n_0), .B0 (b), .B1 (a), .Y (n_2));
  XOR2X1 g43(.A (cin), .B (n_0), .Y (s));
  XOR2X1 g44(.A (b), .B (a), .Y (n_0));
endmodule

module fag_50(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X2 g47(.A0N (n_1), .A1N (cin), .B0 (n_0), .Y (c));
  OAI2BB2X4 g48(.A0N (n_2), .A1N (cin), .B0 (n_2), .B1 (cin), .Y (s));
  INVX1 g49(.A (n_1), .Y (n_2));
  XOR2X1 g50(.A (b), .B (a), .Y (n_1));
  NAND2X1 g51(.A (b), .B (a), .Y (n_0));
endmodule

module fag_49(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2;
  OAI2BB1X2 g41(.A0N (n_1), .A1N (cin), .B0 (n_0), .Y (c));
  MXI2X2 g42(.S0 (cin), .B (n_1), .A (n_2), .Y (s));
  INVX1 g43(.A (n_1), .Y (n_2));
  XOR2X1 g44(.A (a), .B (b), .Y (n_1));
  NAND2X1 g45(.A (a), .B (b), .Y (n_0));
endmodule

module left(p1, a, b);
  input [7:0] a, b;
  output [15:8] p1;
  wire [7:0] a, b;
  wire [15:8] p1;
  wire [41:23] s;
  wire [41:23] c;
  wire [5:0] n;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, z15, z22, z23, z29, z30;
  wire z31, z36, z37, z38, z39, z43, z44, z45;
  wire z46, z47, z50, z51, z52, z53, z54, z55;
  wire z57, z58, z59, z60, z61, z62, z63;
  hag_99 m1(s[23], c[23], z15, z22);
  fag_68 m2(s[25], c[25], s[23], z36, z29);
  hag_98 m3(s[31], c[31], s[25], z43);
  hag_97 m4(s[36], c[36], s[31], z50);
  hag_96 m5(p1[8], n[0], s[36], z57);
  hag_95 m6(s[24], c[24], z23, z30);
  fag_67 m7(s[26], c[26], s[24], c[23], z37);
  hag_94 m8(s[29], c[29], z44, z51);
  fag_66 m9(s[32], c[32], s[29], s[26], c[25]);
  fag_65 m10(s[37], c[37], s[32], c[31], z58);
  fag_64 m11(p1[9], n[1], s[37], c[36], n[0]);
  fag_63 m12(s[27], c[27], z38, z31, c[24]);
  fag_62 m13(s[30], c[30], z45, z52, z59);
  fag_61 m14(s[33], c[33], s[30], s[27], c[26]);
  fag_60 m15(s[38], c[38], s[33], c[29], c[32]);
  fag_59 m16(p1[10], n[2], s[38], c[37], n[1]);
  fag_58 m17(s[28], c[28], z39, z46, z53);
  fag_57 m18(s[34], c[34], s[28], c[27], z60);
  fag_56 m19(s[39], c[39], s[34], c[30], c[33]);
  fag_55 m20(p1[11], n[3], n[2], s[39], c[38]);
  fag_54 m21(s[35], c[35], z47, z54, c[28]);
  fag_53 m22(s[40], c[40], s[35], c[34], z61);
  fag_52 m23(p1[12], n[4], s[40], c[39], n[3]);
  fag_51 m24(s[41], c[41], z55, z62, c[35]);
  fag_50 m25(p1[13], n[5], s[41], c[40], n[4]);
  fag_49 m26(p1[14], p1[15], c[41], z63, n[5]);
  INVX4 g198(.A (n_10), .Y (z22));
  CLKINVX3 g200(.A (n_9), .Y (z39));
  CLKINVX4 g201(.A (n_8), .Y (z46));
  INVX4 g203(.A (n_7), .Y (z36));
  INVX4 g204(.A (n_6), .Y (z15));
  NAND2X2 g206(.A (a[6]), .B (b[2]), .Y (n_10));
  AND2X2 g207(.A (a[2]), .B (b[6]), .Y (z50));
  NAND2X2 g209(.A (a[7]), .B (b[4]), .Y (n_9));
  AND2X2 g210(.A (a[5]), .B (b[7]), .Y (z61));
  NAND2X2 g211(.A (a[6]), .B (b[5]), .Y (n_8));
  AND2X2 g213(.A (a[1]), .B (b[7]), .Y (z57));
  AND2X2 g214(.A (a[4]), .B (b[7]), .Y (z60));
  AND2X2 g215(.A (a[7]), .B (b[5]), .Y (z47));
  NAND2X2 g217(.A (a[4]), .B (b[4]), .Y (n_7));
  NAND2X4 g218(.A (a[7]), .B (b[1]), .Y (n_6));
  CLKINVX3 g219(.A (n_5), .Y (z45));
  INVX4 g222(.A (n_3), .Y (z30));
  INVX4 g223(.A (n_2), .Y (z29));
  INVX2 g226(.A (n_1), .Y (z31));
  INVX2 g227(.A (n_0), .Y (z38));
  NAND2X2 g228(.A (a[5]), .B (b[5]), .Y (n_5));
  AND2X2 g229(.A (a[6]), .B (b[7]), .Y (z62));
  AND2X2 g230(.A (a[7]), .B (b[7]), .Y (z63));
  AND2X2 g231(.A (a[2]), .B (b[7]), .Y (z58));
  NAND2X4 g232(.A (a[7]), .B (b[2]), .Y (n_4));
  NAND2X2 g234(.A (a[6]), .B (b[3]), .Y (n_3));
  NAND2X4 g235(.A (a[5]), .B (b[3]), .Y (n_2));
  AND2X2 g236(.A (a[3]), .B (b[5]), .Y (z43));
  NAND2X4 g239(.A (a[7]), .B (b[3]), .Y (n_1));
  NAND2X4 g240(.A (a[6]), .B (b[4]), .Y (n_0));
  AND2X2 g241(.A (a[7]), .B (b[6]), .Y (z55));
  INVX4 fopt(.A (n_4), .Y (z23));
  AND2X4 g2(.A (a[4]), .B (b[6]), .Y (z52));
  AND2X2 g244(.A (a[3]), .B (b[7]), .Y (z59));
  AND2X2 g245(.A (a[5]), .B (b[6]), .Y (z53));
  AND2X2 g246(.A (a[4]), .B (b[5]), .Y (z44));
  AND2X4 g247(.A (a[5]), .B (b[4]), .Y (z37));
  AND2X2 g248(.A (a[3]), .B (b[6]), .Y (z51));
  AND2X2 g249(.A (a[6]), .B (b[6]), .Y (z54));
endmodule

module hag_93(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  wire n_0, n_2;
  NOR2X1 g20(.A (c), .B (n_2), .Y (s));
  NOR2X1 g21(.A (b), .B (a), .Y (n_2));
  INVX4 g22(.A (n_0), .Y (c));
  NAND2X2 g23(.A (b), .B (a), .Y (n_0));
endmodule

module fag_48(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0;
  XOR3X2 g145(.A (a), .B (cin), .C (b), .Y (s));
  OAI2BB1X2 g146(.A0N (a), .A1N (b), .B0 (n_0), .Y (c));
  OAI21X1 g147(.A0 (b), .A1 (a), .B0 (cin), .Y (n_0));
endmodule

module fag_47(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  OAI2BB1X4 g62(.A0N (n_4), .A1N (cin), .B0 (n_3), .Y (c));
  OAI22XL g63(.A0 (n_0), .A1 (n_6), .B0 (n_5), .B1 (cin), .Y (s));
  INVX1 g64(.A (n_5), .Y (n_6));
  AOI22X1 g65(.A0 (n_1), .A1 (a), .B0 (b), .B1 (n_2), .Y (n_5));
  NAND2X1 g66(.A (n_1), .B (n_2), .Y (n_4));
  NAND2X1 g67(.A (b), .B (a), .Y (n_3));
  INVX1 g69(.A (a), .Y (n_2));
  INVX1 g70(.A (b), .Y (n_1));
  INVXL fopt(.A (cin), .Y (n_0));
endmodule

module rca3bit(s, c, a, b);
  input [2:0] a, b;
  output [2:0] s;
  output c;
  wire [2:0] a, b;
  wire [2:0] s;
  wire c;
  wire c0, c1;
  hag_93 a1(s[0], c0, a[0], b[0]);
  fag_48 a2(s[1], c1, a[1], b[1], c0);
  fag_47 a3(s[2], c, a[2], b[2], c1);
endmodule

module bec5bit(s, a, b, c, d, e);
  input a, b, c, d, e;
  output [4:0] s;
  wire a, b, c, d, e;
  wire [4:0] s;
  wire n_1, n_2, n_3, n_5, n_6, n_7, n_9, n_10;
  MXI2X1 g153(.S0 (n_10), .B (n_1), .A (e), .Y (s[4]));
  NAND2X1 g155(.A (d), .B (n_9), .Y (n_10));
  INVX1 g156(.A (n_6), .Y (n_9));
  NOR2BXL g157(.AN (n_6), .B (n_7), .Y (s[2]));
  NOR2X1 g158(.A (n_5), .B (c), .Y (n_7));
  NAND2X2 g159(.A (n_5), .B (c), .Y (n_6));
  CLKINVX3 g160(.A (n_2), .Y (n_5));
  INVX1 g161(.A (n_3), .Y (s[1]));
  OAI21XL g162(.A0 (b), .A1 (a), .B0 (n_2), .Y (n_3));
  NAND2X1 g163(.A (b), .B (a), .Y (n_2));
  INVX1 g164(.A (e), .Y (n_1));
  MXI2XL g2(.S0 (d), .B (n_9), .A (n_6), .Y (s[3]));
endmodule

module dadda(p, a, b, clk);
  input [7:0] a, b;
  input clk;
  output [15:0] p;
  wire [7:0] a, b;
  wire clk;
  wire [15:0] p;
  wire [10:0] w112;
  wire [15:0] z;
  wire [15:8] w113;
  wire [15:11] w2;
  wire UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6,
       UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED_HIER_Z;
  wire UNCONNECTED_HIER_Z0, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, w1;
  right_da a1({w112[10:3], z[2:0]}, a, b);
  left a2(w113, {a[7:1], UNCONNECTED_HIER_Z}, {b[7:1],
       UNCONNECTED_HIER_Z0});
  rca3bit x1(z[10:8], w1, w113[10:8], w112[10:8]);
  bec5bit x2({w2[15:12], UNCONNECTED3}, w113[11], w113[12], w113[13],
       w113[14], w113[15]);
  CLKBUFX20 g79(.A (n_23), .Y (p[15]));
  CLKBUFX20 g80(.A (n_22), .Y (p[14]));
  DFFX4 \p_reg[15] (.CK (clk), .D (n_6), .Q (n_23), .QN (UNCONNECTED4));
  DFFX4 \p_reg[14] (.CK (clk), .D (n_7), .Q (n_22), .QN (UNCONNECTED5));
  CLKBUFX20 g83(.A (n_20), .Y (p[12]));
  CLKBUFX20 g84(.A (n_21), .Y (p[13]));
  CLKBUFX20 g85(.A (n_19), .Y (p[11]));
  SDFFHQX4 \p_reg[12] (.CK (clk), .D (w2[12]), .SI (w113[12]), .SE
       (n_0), .Q (n_20));
  SDFFHQX4 \p_reg[11] (.CK (clk), .D (w113[11]), .SI (n_1), .SE (w1),
       .Q (n_19));
  OAI21X1 g89(.A0 (w1), .A1 (n_4), .B0 (n_5), .Y (n_7));
  OAI22X1 g90(.A0 (w1), .A1 (n_2), .B0 (n_3), .B1 (n_0), .Y (n_6));
  CLKBUFX20 g91(.A (n_16), .Y (p[8]));
  CLKBUFX16 g92(.A (n_8), .Y (p[0]));
  CLKBUFX20 g93(.A (n_15), .Y (p[7]));
  CLKBUFX16 g94(.A (n_14), .Y (p[6]));
  CLKBUFX16 g95(.A (n_13), .Y (p[5]));
  CLKBUFX20 g96(.A (n_18), .Y (p[10]));
  DFFX4 \p_reg[8] (.CK (clk), .D (z[8]), .Q (n_16), .QN (UNCONNECTED6));
  DFFHQX4 \p_reg[0] (.CK (clk), .D (z[0]), .Q (n_8));
  DFFX4 \p_reg[7] (.CK (clk), .D (w112[7]), .Q (n_15), .QN
       (UNCONNECTED7));
  DFFHQX4 \p_reg[6] (.CK (clk), .D (w112[6]), .Q (n_14));
  DFFHQX4 \p_reg[5] (.CK (clk), .D (w112[5]), .Q (n_13));
  DFFX4 \p_reg[10] (.CK (clk), .D (z[10]), .Q (n_18), .QN
       (UNCONNECTED8));
  CLKBUFX16 g103(.A (n_12), .Y (p[4]));
  CLKBUFX16 g104(.A (n_11), .Y (p[3]));
  CLKBUFX20 g105(.A (n_17), .Y (p[9]));
  CLKBUFX16 g106(.A (n_10), .Y (p[2]));
  CLKBUFX16 g107(.A (n_9), .Y (p[1]));
  DFFHQX4 \p_reg[4] (.CK (clk), .D (w112[4]), .Q (n_12));
  DFFHQX4 \p_reg[3] (.CK (clk), .D (w112[3]), .Q (n_11));
  DFFX4 \p_reg[9] (.CK (clk), .D (z[9]), .Q (n_17), .QN (UNCONNECTED9));
  DFFHQX4 \p_reg[2] (.CK (clk), .D (z[2]), .Q (n_10));
  DFFHQX4 \p_reg[1] (.CK (clk), .D (z[1]), .Q (n_9));
  NAND2X1 g113(.A (w1), .B (w2[14]), .Y (n_5));
  INVX1 g114(.A (w113[14]), .Y (n_4));
  CLKINVX2 g115(.A (w2[15]), .Y (n_3));
  INVX1 g116(.A (w113[15]), .Y (n_2));
  INVX1 g117(.A (w113[11]), .Y (n_1));
  INVX2 g118(.A (w1), .Y (n_0));
  SDFFHQX4 \p_reg[13] (.CK (clk), .D (w2[13]), .SI (w113[13]), .SE
       (n_0), .Q (n_21));
endmodule

